defaults: &defaults
  name: 'kittyballs'
  action: '/stream'
  tokbox:
    apikey: {{ env.TOKBOX_APIKEY }}
    apisecret: {{ env.TOKBOX_APISECRET }}
development:
  <<: *defaults
  port: 5000
  mongo:
    url: mongodb://:@localhost:27017/kittyballs
  redis:
    url: 'redis://:@localhost:6379/'
  session:
    secret: {{ env.SESSION_SECRET }} 
  
test:
  <<: *defaults
  mongo:
    url: {{ env.MONGOHQ_URL }}
  port: {{ env.PORT }}
  redis:
    url: {{ env.REDISTOGO_URL }}
  session:
    secret: {{ env.SESSION_SECRET }} 

production:
  <<: *defaults
  mongo:
    url: {{ env.MONGOHQ_URL }}
  port: {{ env.PORT }}
  redis:
    url: {{ env.REDISTOGO_URL }}
  session:
    secret: {{ env.SESSION_SECRET }} 
